plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.e4gate.seigoime'
    compileSdk 34

    defaultConfig {
        applicationId "com.e4gate.seigoime"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}
