plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.e4gate.seigoime'
    compileSdk 34

    defaultConfig {
        applicationId "com.e4gate.seigoime"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    
    kotlinOptions {
        jvmTarget = '17'
    } // 👈 대표님 코드에서 이 닫는 괄호가 빠져있었습니다!

    // 1. 서명 설정 추가
    signingConfigs {
        release {
            storeFile file("../my-release-key.jks")
            storePassword "ws010310"
            keyAlias "my-key-alias"
            keyPassword "ws010310"
        }
    }

    buildTypes {
        release {
            // 2. 위에서 만든 서명 설정을 적용
            signingConfig signingConfigs.release
          
            // 코드 최적화 및 리소스 축소 (앱 용량이 더 줄어듭니다)
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
         }
    }
}
    
dependencies {
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
}