name: Build Android APK
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 1. 내 코드 가져오기
      uses: actions/checkout@v4

    - name: 2. 자바(JDK) 개발 환경 세팅
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: 2-5. 전용 조립 엔진(8.2) 세팅하기
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2'

    - name: 3. 안드로이드 앱 빌드 (APK 생성)
      run: gradle assembleRelease

    - name: 4. 완성된 APK 파일 다운로드할 수 있게 올리기
      uses: actions/upload-artifact@v4
      with:
        name: SeigoIME_release-app
        path: app/build/outputs/apk/release/*.apk
